### ISSUE TITLE
FEATURE: Basic keyboard shortcuts

### ISSUE THREAD

**Issue by foo-dogsquared** [foo-dogsquared/virtual-idea-dice#3]
Just for convenience sake, let's define the following keyboard shortcuts:

- `F1` - Help (implemented since #9)
- `Ctrl + Z` - Undo deleted dice in the app screen (implemented since #8)
- `Ctrl + G` - **G**enerate ideas (implemented since #8)
- `Ctrl + D` - Clear ideas (implemented since #8)
- `Ctrl + Shift + N` - Add a **n**ew die (implemented since #8, changed into current keystroke since #9)
- `Ctrl + E` - **E**xport dice (implemented since #8)
- `Ctrl + I` - **I**mport dice (implemented since #8)
- `Ctrl + S` - **S**ave dice results (implemented since #8)

EDIT: Since #8, there has been quite a few changes aside from the edits above:

- `Ctrl + Delete` - Remove current die on the carousel. (implemented since #8)
- `Ctrl + Shift + L` - Lock all of the dice. (implemented since #9)
- `Ctrl + Shift + :` - Unlock all of the dice. (implemented since #9)
- `Ctrl + Shift + "` - Toggle the lock all of the dice. (implemented since #9)

Suggestions about this are quite appreciated!

**Comment by brownbonnie** [comment]
Is this still something you'd like to have implemented?

**Comment by foo-dogsquared** [comment]
Yup, I still want this to be implemented. I just eventually have this one flew away since I'm mostly using this on my phone now. Thanks for reminding me. :+1:

**Comment by brownbonnie** [comment]
No problem :) I was going to have a look into it further and see if I could help out, would that be ok?

**Comment by foo-dogsquared** [comment]
Of course! You can start looking into the `develop` branch for upcoming updates to be brought over. I've already started working on some of the things I want to implement.

**Comment by foo-dogsquared** [comment]
Closing this issue now since I've implemented all of the keyboard shortcuts I've listed from the start.
